-- Clear existing data first
DELETE FROM challenges;
DELETE FROM games;
DELETE FROM rewards;

-- Insert 20 challenges
INSERT INTO challenges (title, description, points, difficulty, is_active) VALUES
  ('Active Chores', 'Turn chores into an active challenge', 5, 'easy', true),
  ('Bedtime Stretch', 'Stretch before bed', 5, 'easy', true),
  ('Dance Marathon', 'Have a dance party together', 5, 'easy', true),
  ('Family Balance', 'Hold tree pose together for 20 seconds', 5, 'easy', true),
  ('Freeze Dance', 'Dance when the music plays, freeze when it stops', 5, 'easy', true),
  ('Nature Scavenger Hunt', 'Find items on a nature walk checklist', 5, 'easy', true),
  ('Step Together', 'Walk 2,000 steps together as a family', 5, 'easy', true),
  ('7-Day Step Streak', 'Hit daily step goal every day for a week', 10, 'medium', true),
  ('Active Transport Week', 'Walk, bike, or scooter to destinations all week', 10, 'medium', true),
  ('Couch Potato Detox', 'No screens during daylight hours for a day', 10, 'medium', true),
  ('Daily Dance Party', 'Have a dance party every day for a week', 10, 'medium', true),
  ('Evening Walk Routine', 'Take a post-dinner walk every day for a week', 10, 'medium', true),
  ('Family Fitness Challenge', 'Complete assigned exercises every day for a week', 10, 'medium', true),
  ('Family Relay', 'Each family member does a short activity in sequence', 10, 'medium', true),
  ('Morning Movement', 'Do 5 minutes of movement right after waking up', 10, 'medium', true),
  ('Outdoor Adventure', 'Visit a new outdoor space (park, trail, etc.)', 10, 'medium', true),
  ('Family 5K', 'Walk or run a 5K together', 15, 'hard', true),
  ('Hike a Trail', 'Complete a family hike on a local trail', 15, 'hard', true),
  ('Mini Triathlon', 'Complete swim, bike, and run activities in one day', 15, 'hard', true),
  ('Weekend Warrior', 'Complete 3 outdoor activities in one weekend', 15, 'hard', true);

-- Insert 44 games
INSERT INTO games (id, title, description, category, points) VALUES
  (gen_random_uuid(), 'Family Relay', 'Each family member does a short activity in sequence', 'adventure', 10),
  (gen_random_uuid(), 'Family Tug Circle', 'Everyone pulls rope in circle, last standing wins', 'adventure', 10),
  (gen_random_uuid(), 'Flashlight Tag', 'Tag using flashlight beams in the dark', 'adventure', 10),
  (gen_random_uuid(), 'Glow Stick Dance', 'Dance in the dark with glow sticks', 'adventure', 10),
  (gen_random_uuid(), 'Hula Hoop Contest', 'See who can keep the hoop going longest', 'adventure', 10),
  (gen_random_uuid(), 'Indoor Bowling', 'Use bottles and a soft ball to bowl indoors', 'adventure', 10),
  (gen_random_uuid(), 'Laser Maze', 'Crawl through a hallway of streamer lasers', 'adventure', 10),
  (gen_random_uuid(), 'Mini Olympics', 'Set up 3-5 mini events and compete', 'adventure', 10),
  (gen_random_uuid(), 'Nature Scavenger Hunt', 'Find items on a nature walk checklist', 'adventure', 10),
  (gen_random_uuid(), 'Obstacle Course', 'Build a course with pillows, chairs, etc.', 'adventure', 10),
  (gen_random_uuid(), 'Parachute Play', 'Use a sheet as a parachute for games', 'adventure', 10),
  (gen_random_uuid(), 'Park Playground Tour', 'Visit a new playground and try all equipment', 'adventure', 10),
  (gen_random_uuid(), 'Puddle Jumping', 'Jump in puddles after it rains', 'adventure', 10),
  (gen_random_uuid(), 'Shadow Tag', 'Tag by stepping on each other''s shadows', 'adventure', 10),
  (gen_random_uuid(), 'Treasure Hunt', 'Hide clues around the house or yard', 'adventure', 10),
  (gen_random_uuid(), 'Animal Walks', 'Move like different animals across the room', 'exercise', 10),
  (gen_random_uuid(), 'Balance Beam', 'Walk a tape line without stepping off', 'exercise', 10),
  (gen_random_uuid(), 'Ball Toss', 'Toss a ball back and forth, increasing distance', 'exercise', 10),
  (gen_random_uuid(), 'Bubble Pop', 'Pop bubbles as fast as you can', 'exercise', 10),
  (gen_random_uuid(), 'Family Plank', 'See who can hold a plank the longest', 'exercise', 10),
  (gen_random_uuid(), 'Family Yoga', 'Follow a kid-friendly yoga video together', 'exercise', 10),
  (gen_random_uuid(), 'Hopscotch', 'Draw and play hopscotch', 'exercise', 10),
  (gen_random_uuid(), 'Jump Rope Relay', 'Take turns jumping rope in a relay', 'exercise', 10),
  (gen_random_uuid(), 'Jumping Jacks Race', 'See who can do 20 jumping jacks fastest', 'exercise', 10),
  (gen_random_uuid(), 'Pillow Fight Fitness', 'Safe pillow fight with movement rules', 'exercise', 10),
  (gen_random_uuid(), 'Red Light Green Light', 'Classic movement game', 'exercise', 10),
  (gen_random_uuid(), 'Sock Skating', 'Slide around in socks on hard floors', 'exercise', 10),
  (gen_random_uuid(), 'Stair Climb Challenge', 'Race up and down stairs safely', 'exercise', 10),
  (gen_random_uuid(), 'Stretching Story', 'Stretch while acting out a story', 'exercise', 10),
  (gen_random_uuid(), 'Balloon Volleyball', 'Keep the balloon off the ground', 'fun', 10),
  (gen_random_uuid(), 'Dance Freeze', 'Dance when music plays, freeze when it stops', 'fun', 10),
  (gen_random_uuid(), 'Dance Off', 'Take turns showing off dance moves', 'fun', 10),
  (gen_random_uuid(), 'Dice Fitness', 'Roll dice and do that many of an exercise', 'fun', 10),
  (gen_random_uuid(), 'Duck Duck Goose', 'Classic game with running', 'fun', 10),
  (gen_random_uuid(), 'Follow the Leader', 'Leader does movements, others copy', 'fun', 10),
  (gen_random_uuid(), 'Four Corners', 'Run to corners based on caller''s choice', 'fun', 10),
  (gen_random_uuid(), 'Hide and Seek', 'Classic game with hiding and seeking', 'fun', 10),
  (gen_random_uuid(), 'Musical Chairs', 'Walk around chairs, sit when music stops', 'fun', 10),
  (gen_random_uuid(), 'Musical Statues', 'Dance, then freeze like a statue', 'fun', 10),
  (gen_random_uuid(), 'Paper Plate Skating', 'Skate on carpet using paper plates', 'fun', 10),
  (gen_random_uuid(), 'Silly Walk Race', 'Race using the silliest walk possible', 'fun', 10),
  (gen_random_uuid(), 'Simon Says', 'Follow commands only when Simon says', 'fun', 10),
  (gen_random_uuid(), 'Sock Toss', 'Toss rolled socks into a basket', 'fun', 10),
  (gen_random_uuid(), 'What Time Is It Mr. Wolf?', 'Creep up and run when the wolf chases', 'fun', 10);

-- Insert 45 rewards
INSERT INTO rewards (title, description, cost, type, is_active) VALUES
  ('Family Movie Night', 'Pick a family movie and watch together with snacks', 180, 'family', true),
  ('Ice Cream Outing', 'Family trip for ice cream cones', 200, 'family', true),
  ('Picnic in the Park', 'Pack a lunch and enjoy it outdoors', 180, 'family', true),
  ('Game Night Choice', 'Pick the game for family game night', 120, 'family', true),
  ('Pizza Party', 'Family makes or orders pizza together', 200, 'family', true),
  ('Backyard Camping', 'Set up a tent in the backyard for a night', 250, 'family', true),
  ('Fort Building', 'Build an epic blanket fort together', 100, 'family', true),
  ('Bike Ride Adventure', 'Family bike ride to a fun destination', 180, 'family', true),
  ('Breakfast for Dinner', 'Make pancakes and breakfast foods for dinner', 120, 'family', true),
  ('Zoo or Aquarium Trip', 'Family outing to see the animals', 350, 'family', true),
  ('Mini Golf Outing', 'Play a round of mini golf together', 250, 'family', true),
  ('Bake Cookies Together', 'Make and decorate cookies as a family', 150, 'family', true),
  ('Stargazing Night', 'Stay up late and watch the stars', 150, 'family', true),
  ('Water Park Day', 'Sprinklers, water balloons, or pool fun', 200, 'family', true),
  ('Family Photo Shoot', 'Take silly and fun family photos', 100, 'family', true),
  ('Extra Screen Time', '30 minutes of extra screen time', 80, 'individual', true),
  ('Stay Up Late', 'Stay up 30 minutes past bedtime', 100, 'individual', true),
  ('Choose Dinner', 'Pick what the family eats for dinner', 120, 'individual', true),
  ('New Book', 'Pick a new book to read', 150, 'individual', true),
  ('Favorite Snack', 'Get your favorite snack from the store', 80, 'individual', true),
  ('Friend Playdate', 'Invite a friend over to play', 180, 'individual', true),
  ('Bubble Bath', 'Enjoy a relaxing bubble bath with toys', 60, 'individual', true),
  ('Art Supplies', 'Get new crayons, markers, or art supplies', 120, 'individual', true),
  ('Skip a Chore', 'Skip one assigned chore for the day', 100, 'individual', true),
  ('Breakfast in Bed', 'Have breakfast delivered to your bed', 120, 'individual', true),
  ('Pick the Music', 'Control the music for a whole day', 80, 'individual', true),
  ('New Small Toy', 'Pick a small toy from the store', 200, 'individual', true),
  ('Pajama Day', 'Stay in pajamas all day (on a day off)', 80, 'individual', true),
  ('Special Dessert', 'Get a special dessert of your choice', 100, 'individual', true),
  ('Extra Story Time', 'Extra bedtime story from a parent', 60, 'individual', true),
  ('Trophy or Medal', 'Get a fun trophy or medal', 350, 'special', true),
  ('Hall of Fame Wall', 'Photo added to family hall of fame', 250, 'special', true),
  ('Custom T-Shirt', 'Design and order a custom t-shirt', 400, 'special', true),
  ('Adventure Day', 'Pick an adventure activity for the family', 500, 'special', true),
  ('Chore-Free Week', 'No chores for an entire week', 400, 'special', true),
  ('New Sports Equipment', 'Pick new sports gear (ball, frisbee, etc.)', 300, 'special', true),
  ('Trampoline Time', 'Trip to a trampoline park', 350, 'special', true),
  ('Bowling Outing', 'Family bowling night', 300, 'special', true),
  ('Arcade Trip', 'Visit an arcade with game tokens', 350, 'special', true),
  ('Theme Park Day', 'Trip to a local amusement park', 600, 'special', true),
  ('Sleepover Permission', 'Host or attend a sleepover', 300, 'special', true),
  ('New Game or Toy', 'Pick a new game or toy (up to $20)', 400, 'special', true),
  ('Restaurant Choice', 'Pick the restaurant for a family dinner out', 300, 'special', true),
  ('VIP Day', 'Be treated like a VIP for a whole day', 450, 'special', true),
  ('Pet Store Visit', 'Trip to pet store to see the animals', 200, 'special', true);