// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dakkxcyqfmywmeemzkbe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRha2t4Y3lxZm15d21lZW16a2JlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczNDg2NzYsImV4cCI6MjA3MjkyNDY3Nn0.gCDNmzGCVs1iOj86tWAb0Y6tRULpE5S1MCcCkyG3tk0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});